### ISSUE TITLE
Portfolio Page Image Hover Opacity 

### ISSUE THREAD

**Issue by norr0065** [norr0065/portfolio-site#11]
Hey @robinbastien 

So what I'm trying to do is what I showed you at work. All I want is the images to have a slight opacity change when hovered over.  Where I get slightly confused as to what I style - Each picture using the  "portfolioimage" class or create a new class and put it in the img class tag aswell?  

 ( I know it's due to the jimmy rigged grid I've created - which I've finally gotten perfect) 

Sorry not trying to be confusing. I've tried to attack the hover / hover with title aspect of this grid a couple of times and have ruined other main elements in the process. 

B

**Comment by robinbastien** [comment]
Hey @norr0065 

Cool! I'll post snippets below you can use. Add these to existing .tallportfolioimage and .portfolioimage classes :)

``` CSS

/* Option 1: This will fade the images on hover, producing a lighter hover state since there's a white BG */
.portfolioimage,
.tallportfolioimage {
-webkit-transition: all 0.3s ease-out;
   -moz-transition: all 0.3s ease-out;
     -ms-transition: all 0.3s ease-out;
         transition: all 0.3s ease-out;
}

.portfolioimage:hover,
.tallportfolioimage:hover {
   opacity: 0.8;
}

/* Option 2: This will make all portfolio items darker by default, but the hover state makes them brighten to their original image. It's a schweet effect. Doesn't work in older browsers though. */

.portfolioimage,
.tallportfolioimage {
-webkit-filter: brightness(0.8);
        filter: brightness(0.8);
-webkit-transition: all 0.3s ease-out;
   -moz-transition: all 0.3s ease-out;
     -ms-transition: all 0.3s ease-out;
         transition: all 0.3s ease-out;
}

.portfolioimage:hover,
.tallportfolioimage:hover {
-webkit-filter: brightness(1);
        filter: brightness(1);
}
```

Oh, one tip for naming classes is try to group all things of one type with the same class, and if there's ones that are different from the others, you can add additional classes. You don't have to do this of course, just a tip for the future :)

``` HTML
<!-- Example -->
<img class="portfolioimage" src="/portfolio-site/images/ignitedbsadsqare.jpg" alt="Ignited Potential">
<img class="portfolioimage portfolioimage--tall" src="/portfolio-site/images/ignitedbsadsqare.jpg" alt="Ignited Potential">
```

That way, you have one to use for all .portfolioimage's in CSS, and another just for changing the height of the portfolio images that are taller :p. if you do this, the above CSS will only need the .portfolioimage class.

Good stuff, your portfolio looks good!
